export const surpriseMePrompts = [
  "A futuristic city skyline at sunset",
  "A mermaid lounging on a rock in a turquoise sea",
  "An alien planet with two moons and unusual plants",
  "A pirate ship sailing through a sea storm",
  "A steampunk robot playing a violin",
  "A tranquil Zen garden with cherry blossom trees",
  "A haunted Victorian mansion at midnight",
  "A caveman inventing the wheel",
  "A family of unicorns in a magical forest",
  "A cozy cabin in a snow-covered mountain landscape",
  "A cat astronaut exploring Mars",
  "A dolphin diving into a wave in the shape of a heart",
  "A magician casting a spell, with magic swirling from his wand",
  "A deep-sea scene with exotic fishes and a sunken treasure chest",
  "A surreal landscape with floating islands and waterfalls in the sky",
  "A knight facing a fire-breathing dragon",
  "A cyberpunk city with neon lights and hovercars",
  "A gnome village hidden among the roots of a giant tree",
  "An enchanted forest with glowing mushrooms and fairy creatures",
  "A chef cooking in a busy gourmet kitchen",
  "An ice palace in the Arctic with aurora borealis in the sky",
  "A superhero dog saving a kitten from a tree",
  "A jazz band performing on a New Orleans street",
  "A detective in a noir-themed rainy cityscape",
  "A tea party in Alice in Wonderland",
  "A zombie apocalypse in a shopping mall",
  "A flock of phoenixes rising from ashes",
  "A wild west scene with cowboys and a train robbery",
  "A royal court in a fantasy kingdom",
  "A ninja cat fighting robot mice",
  "A dinosaur-themed amusement park",
  "A robot butler serving at a high-tech party",
  "A romantic sunset over Paris with Eiffel Tower view",
  "A secret door in a library leading to a mystical land",
  "A space station orbiting a green gas giant",
  "A peaceful hobbit village in the Shire",
  "An epic battle between pirates and kraken",
  "A mountaintop monastery in the Himalayas",
  "A post-apocalyptic city reclaimed by nature",
  "A Venetian carnival with elaborate masks and gondolas",
  "Santa's workshop at the North Pole",
  "A sushi restaurant run by anthropomorphic cats",
  "A labyrinth garden with a minotaur statue",
  "An undersea city populated by merpeople",
  "A fairy-tale princess dancing with a bear",
  "A pair of astronauts playing chess on the moon",
  "A sunrise scene with hot air balloons over Cappadocia",
  "A giant panda playing in a bamboo forest",
  "An ancient Egyptian tomb with hidden traps and treasures",
  "A samurai duel during the cherry blossom season",
];
